require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '.git/**/*'
    - '*.csv'
    - '*.json'
    - '*.yml'

#
# Performance
#
Performance:
  Exclude:
    - '**/test/**/*'

#
# RuboCop built-in settings.
#   For documentation on all settings see: https://docs.rubocop.org/rubocop/
#

Layout/DotPosition:
  EnforcedStyle: trailing

# Turn on auto-correction of equals alignment.
Layout/EndAlignment:
  AutoCorrect: true

# Prevent accidental windows line endings
Layout/EndOfLine:
  EnforcedStyle: lf

# Autocorrect equals sign alignment.
Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

# Use a table layout for hashes
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 128

# Match existing layout
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/ParameterLists:
  CountKeywordArgs: false

# Does not allow Symbols to load
Security/YAMLLoad:
  AutoCorrect: false

# TODO: Soften Limits for phase 1 only
Style/Documentation:
  Enabled: false

# One line methods
Style/EmptyMethod:
  EnforcedStyle: expanded

# Ruby 3 compatibility feature
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  AutoCorrect: true

# Incorrectly changes job.fail to job.raise
Style/SignalException:
  Enabled: false

# Since English may not be loaded, cannot force its use.
Style/SpecialGlobalVars:
  Enabled: false

# Make it easier for developers to move between languages.
Style/StringLiterals:
  EnforcedStyle: double_quotes
